/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.membership.management.system;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class ModifyMember extends javax.swing.JFrame {

    /**
     * Creates new form ModifyMember
     */
    public ModifyMember() {
        initComponents();
        contacttxt.setTransferHandler(null);
        idtxt.setTransferHandler(null);
        lblid.setVisible(false);
        lblcontact.setVisible(false);
        lblmtype.setVisible(false);
        lblreg.setVisible(false);
        lblfee.setVisible(false);
        btnupdate.setEnabled(false);
        mtype.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncancel = new javax.swing.JButton();
        mtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        contacttxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lblcontact = new javax.swing.JLabel();
        lblmtype = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        lblfee = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncancel.setText("Back");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        mtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Non-Deluxe", "Week-Day" }));
        mtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Membership Type :");

        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });
        contacttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contacttxtKeyTyped(evt);
            }
        });

        jLabel5.setText("Registration Fees :");

        reg.setText(" ");

        jLabel1.setText("Name :");

        jLabel7.setText("Monthly Fees :");

        jLabel2.setText("Contact Number :");

        fee.setText(" ");

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lblname.setText(" ");

        jLabel8.setText("Member's ID :");

        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtxtKeyTyped(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        lblid.setText("id");

        lblcontact.setText("con");

        lblmtype.setText("type");

        lblreg.setText("reg");

        lblfee.setText("fee");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Edit Member");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblcontact)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblmtype)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblreg))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(contacttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfee)
                                    .addComponent(idtxt)
                                    .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsearch)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(btncancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfee)
                    .addComponent(lblreg)
                    .addComponent(lblmtype)
                    .addComponent(lblid)
                    .addComponent(lblcontact))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fee))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btncancel)
                    .addComponent(btnExit))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String search = lblid.getText() +"\t\t"+lblname.getText()+"\t\t"+lblcontact.getText()+"\t\t"+lblmtype.getText()+"\t\t"+lblreg.getText()+"\t\t"+lblfee.getText();
        String replacement = lblid.getText()+"\t\t"+lblname.getText()+"\t\t"+contacttxt.getText()+"\t\t"+mtype.getSelectedItem()+"\t\t"+reg.getText()+"\t\t"+fee.getText();
        int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to make changes on this record?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        try {
        
        BufferedReader file = new BufferedReader(new FileReader("database.txt"));
        String line;String input = "";
        while ((line = file.readLine()) != null) input += line + "\r\n";
        file.close();

        
        
        
        input = input.replace(search, replacement); 
        
       

        
        FileOutputStream fileOut = new FileOutputStream("database.txt");
        fileOut.write(input.getBytes());
        fileOut.close();

    } catch (Exception e) {
        
    }
        javax.swing.JOptionPane.showMessageDialog(this, "Successfully Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new StaffMenu().setVisible(true);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void mtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtypeActionPerformed
        // TODO add your handling code here:
        String membertype; 
        membertype = (String)mtype.getSelectedItem();
        switch (membertype) {
            case "Deluxe":
                reg.setText("RM500");
                fee.setText("RM120");
                break;
            case "Non-Deluxe":
                reg.setText("RM300");
                fee.setText("RM100");
                break;
            case "Week-Day":
                reg.setText("RM180");
                fee.setText("RM75");
                break;
            default:
                break;
        }

    }//GEN-LAST:event_mtypeActionPerformed

    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contacttxtActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        File db = new File("database.txt");
        String uid = idtxt.getText();
        Boolean idfound = false;  
        try{
            Scanner read = new Scanner(db);
            while(read.hasNextLine()){
                String nl = read.nextLine();
                String column[]=nl.split("\t\t");
                if(column[0].equals(uid)){
                    lblid.setText(column[0]);
                    lblname.setText(column[1]);
                    contacttxt.setText(column[2]);
                    lblcontact.setText(column[2]);
                    mtype.setSelectedItem(column[3]);
                    lblmtype.setText(column[3]);
                    reg.setText(column[4]);
                    lblreg.setText(column[4]);
                    fee.setText(column[5]);
                    lblfee.setText(column[5]);
                    idfound = true;
                    btnupdate.setEnabled(true);
                    mtype.setEnabled(true);
                    javax.swing.JOptionPane.showMessageDialog(this, "ID found","Information",JOptionPane.INFORMATION_MESSAGE);
                    break;
                    }
                else{
                    idfound = false;
                }
                    
                
            }
            if(idfound == false){
                javax.swing.JOptionPane.showMessageDialog(this, "ID not found","Error",JOptionPane.ERROR_MESSAGE);
                    btnupdate.setEnabled(false);
                    mtype.setEnabled(false);
                    lblname.setText("");
                    contacttxt.setText("");
                    mtype.setSelectedItem("");
                    reg.setText("");
                    fee.setText("");
            }
            
            

        }catch(FileNotFoundException e){
            //handle this
        } 
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffMenu().setVisible(true);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Confirm to exit program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      System.exit(0);
    }  
    }//GEN-LAST:event_btnExitActionPerformed

    private void idtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_idtxtKeyTyped

    private void contacttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttxtKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_contacttxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JLabel fee;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblcontact;
    private javax.swing.JLabel lblfee;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblmtype;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblreg;
    private javax.swing.JComboBox<String> mtype;
    private javax.swing.JLabel reg;
    // End of variables declaration//GEN-END:variables
}
