/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.membership.management.system;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric
 */
public class PaymentSystem extends javax.swing.JFrame {

    /**
     * Creates new form PaymentSystem
     */
    public PaymentSystem() {
        initComponents();
        btnpay.setEnabled(false);
        btnrecord.setEnabled(false);
        txtid.setTransferHandler(null);
        lblid.setVisible(false);
        lblcon.setVisible(false);
        lbltype.setVisible(false);
        lblreg.setVisible(false);
        lblfee1.setVisible(false);
        lbluserid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblbill = new javax.swing.JLabel();
        lblfee = new javax.swing.JLabel();
        btnrecord = new javax.swing.JButton();
        btnpay = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        lblstat = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblcon = new javax.swing.JLabel();
        lbltype = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        lblfee1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrec = new javax.swing.JTextArea();
        lbluserid = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Member's ID : ");

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Name : ");

        jLabel4.setText("Latest Bill Date : ");

        jLabel5.setText("Overdue Amount : ");

        lblname.setText(" ");

        lblbill.setText(" ");

        lblfee.setText(" ");

        btnrecord.setText("View Payment Record");
        btnrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecordActionPerformed(evt);
            }
        });

        btnpay.setText("Pay Now");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        status.setText("Status : ");

        lblstat.setText(" ");

        lblid.setText("jLabel3");

        lblcon.setText("jLabel3");

        lbltype.setText("jLabel3");

        lblreg.setText("jLabel3");

        lblfee1.setText("jLabel3");

        txtrec.setColumns(20);
        txtrec.setRows(5);
        jScrollPane1.setViewportView(txtrec);

        lbluserid.setText("jLabel3");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Payment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblid)
                                .addGap(18, 18, 18)
                                .addComponent(lblcon)
                                .addGap(18, 18, 18)
                                .addComponent(lbltype)
                                .addGap(18, 18, 18)
                                .addComponent(lblreg)
                                .addGap(18, 18, 18)
                                .addComponent(lblfee1)
                                .addGap(18, 18, 18)
                                .addComponent(lbluserid)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnpay)
                                        .addGap(54, 54, 54)
                                        .addComponent(btnrecord)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnback)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnExit))
                                    .addComponent(btnsearch))
                                .addContainerGap(112, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(status)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(lblbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblstat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(383, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(lblstat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblbill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblfee))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpay)
                    .addComponent(btnrecord)
                    .addComponent(btnback)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(lblcon)
                    .addComponent(lbltype)
                    .addComponent(lblreg)
                    .addComponent(lblfee1)
                    .addComponent(lbluserid))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        File db = new File("database.txt");
        String uid = txtid.getText();
        Boolean idfound = false;  
        try{
            Scanner read = new Scanner(db);
            while(read.hasNextLine()){
                String nl = read.nextLine();
                String column[]=nl.split("\t\t");
                if(column[0].equals(uid) && column[6].equals("New")){
                    lblid.setText(column[0]);
                    lblname.setText(column[1]);
                    lblcon.setText(column[2]);
                    lbltype.setText(column[3]);
                    lblreg.setText(column[4]);
                    lblfee1.setText(column[5]);
                    lblstat.setText(column[6]);
                    lblbill.setText(column[7]);
                    String strreg= column[4].replaceAll("[^0-9]", "");
                    String strfee= column[5].replaceAll("[^0-9]", "");
                    int fee = Integer.parseInt(strfee);
                    int reg = Integer.parseInt(strreg);
                    int total = reg + fee;
                    String strtotal = Integer.toString(total);
                    lblfee.setText("RM"+strtotal);
                    idfound = true;             
                    btnpay.setEnabled(true);
                    btnrecord.setEnabled(true);
                    javax.swing.JOptionPane.showMessageDialog(this, "ID found","Information",JOptionPane.INFORMATION_MESSAGE);
                    break;
                    }
                else if(column[0].equals(uid) && column[6].equals("Active")){
                    lblid.setText(column[0]);
                    lblname.setText(column[1]);
                    lblcon.setText(column[2]);
                    lbltype.setText(column[3]);
                    lblreg.setText(column[4]);
                    lblfee1.setText(column[5]);
                    lblstat.setText(column[6]);
                    lblbill.setText(column[7]);
                    Date date1 = DateFormat.getDateInstance().parse(column[7]);
                    Date today = new Date();
                    if (date1.before(today)){
                        long diff = today.getTime() - date1.getTime();
                        Calendar c = Calendar.getInstance();
                        c.setTimeInMillis(diff);
                        int mMonth = c.get(Calendar.MONTH)+1;
                        String strfee= column[5].replaceAll("[^0-9]", "");
                        int fee = Integer.parseInt(strfee);
                        int total = fee*mMonth;
                        lblfee.setText("RM"+total);
                    }
                    else {
                        
                        lblfee.setText("RM0");
                    }
                        
                    idfound = true;
                    btnpay.setEnabled(true);
                    btnrecord.setEnabled(true);
                    javax.swing.JOptionPane.showMessageDialog(this, "ID found","Information",JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
                else{
                    idfound = false;
                }
                    
                
            }
            if(idfound == false){
                javax.swing.JOptionPane.showMessageDialog(this, "ID not found","Error",JOptionPane.ERROR_MESSAGE);
                    
                    lblname.setText("");
                    lblstat.setText("");
                    lblbill.setText("");
                    lblfee.setText("");
            }
            
            

        }catch(FileNotFoundException e){
            //handle this
        } catch (ParseException ex) {
            Logger.getLogger(PaymentSystem.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StaffMenu().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        try {
            // TODO add your handling code here:
            String strdate = lblbill.getText();
            Date date1 = DateFormat.getDateInstance().parse(strdate);
            Calendar myCal = Calendar.getInstance();
            myCal.setTime(date1);    
            myCal.add(Calendar.MONTH, +1);    
            date1 = myCal.getTime();
            String stringDate = DateFormat.getDateInstance().format(date1);
            String search = lblid.getText() +"\t\t"+lblname.getText()+"\t\t"+lblcon.getText()+"\t\t"+lbltype.getText()+"\t\t"+lblreg.getText()+"\t\t"+lblfee1.getText()+"\t\t"+lblstat.getText()+"\t\t"+lblbill.getText();
            String replacement = lblid.getText() +"\t\t"+lblname.getText()+"\t\t"+lblcon.getText()+"\t\t"+lbltype.getText()+"\t\t"+lblreg.getText()+"\t\t"+lblfee1.getText()+"\t\t"+"Active"+"\t\t"+stringDate;
            int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to pay your fee?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    
                    BufferedReader file = new BufferedReader(new FileReader("database.txt"));
                    String line;String input = "";
                    while ((line = file.readLine()) != null) input += line + "\r\n";
                    file.close();
                    
                    
                    
                    
                    input = input.replace(search, replacement);
                    
                    
                    
                    
                    FileOutputStream fileOut = new FileOutputStream("database.txt");
                    fileOut.write(input.getBytes());
                    fileOut.close();
                    
                } catch (Exception e) {
                    
                }
                
                FileWriter writer;
        try {
            writer = new FileWriter("payment.txt", true);
        
            writer.write(lblid.getText() + " \t\t" + lblname.getText() + "\t\t" + lblbill.getText() + "\t\t" + lblfee.getText() + "\t\t" + Login.username);
        
            writer.write("\r\n");
            writer.close();
            } catch (IOException ex) {
            Logger.getLogger(InsertNewMember.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
                javax.swing.JOptionPane.showMessageDialog(this, "Successfully Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new StaffMenu().setVisible(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(PaymentSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnpayActionPerformed

    private void btnrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordActionPerformed
        // TODO add your handling code here:
        File file =new File("payment.txt");
        Scanner in = null;
        try {
            in = new Scanner(file);
            while(in.hasNext())
            {
                String line=in.nextLine();
                if(line.contains(lblid.getText()+" 		"+lblname.getText()))
                    txtrec.setText(line+"\n" + txtrec.getText());

            }
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnrecordActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Confirm to exit program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      System.exit(0);
    }  
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnrecord;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lblcon;
    private javax.swing.JLabel lblfee;
    private javax.swing.JLabel lblfee1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblreg;
    private javax.swing.JLabel lblstat;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JLabel status;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextArea txtrec;
    // End of variables declaration//GEN-END:variables
}
